name: Bug Report | گزارش مشکل
description: Report a bug encountered while using BPB Panel
body:
    - type: markdown
      attributes:
          value: |
              Please make sure to provide a descriptive report. It saves time for both the developer and users who are looking for solutions. Providing as much information as possible, including screenshots and logs, is highly appreciated. This will help us to better understand the issue and respond more effectively.
              لطفا مطمئن شوید که گزارشی تشریحی ارائه دهید. این باعث می‌شود که توسعه‌دهنده و کاربرانی که در جستجوی راهکارها هستند، زمان کمتری صرف کنند. ارائه اطلاعات بیشتر از جمله اسکرین‌شات و لاگ توصیه می‌شود. این باعث می‌شود که ما بهتر بتوانیم مشکل را درک کرده و به‌صورت بهتر پاسخ دهیم.
    - type: checkboxes
      id: confirm-search
      attributes:
          label: Attention | توجه
          description: |
            Please search [existing issues](https://github.com/bia-pain-bache/BPB-Worker-Panel/issues) and read [FAQ](https://bia-pain-bache.github.io/BPB-Worker-Panel/faq/) before reporting.<br>
            لطفا قبل از ارسال گزارش [ایشوهای موجود](https://github.com/bia-pain-bache/BPB-Worker-Panel/issues) و مخصوصا [سوالات متداول](https://bia-pain-bache.github.io/BPB-Worker-Panel/faq/) را بررسی کنید.
          options:
              - label: I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد
                required: true
              - label: I read FAQ and no relevant issues were found | سوالات متداول را خواندم و هیچ مورد مربوطی پیدا نشد
                required: true
    - type: textarea
      id: problem
      attributes:
          label: What Happened? | چه اتفاقی افتاده؟
          description: |
              Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.<br>
              لطفاً اطلاعات کاملی را ارائه دهید. اگر این کار را انجام ندهید، ممکن است مشکل شما به صورت تمام شده تلقی شده یا در زمان مناسبی بررسی نشود.
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: Minimal Reproducible Example | چه فرایندی برای مشاهده این مشکل طی کرده‌اید؟
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
    - type: textarea
      id: logs
      attributes:
          label: Relevant log output | لاگ برنامه یا پنل
          description: |
            Refer to the client logs if you have connection issues, otherwise paste panel error.<br>
            اگر مشکل اتصال دارید به قسمت لاگ فیلترشکن بروید و در غیر اینصورت خطای پنل را اینجا کپی دهید. 
          render: shell
      validations:
          required: true
    - type: input
      id: panel-version
      attributes:
          label: Panel version | نسخه‌ پنل
      validations:
          required: true
    - type: input
      id: client-name
      attributes:
          label: Client | برنامه فیلترشکن
          description: |
              Please specify the client application you are using, necessary for connection troubleshooting.<br>
              نام برنامه فیلترشکنی که استفاده می‌کنید را مشخص کنید، برای عیب‌یابی مشکلات اتصال الزامی است.
      validations:
          required: false
    - type: input
      id: client-version
      attributes:
          label: Client version | نسخه برنامه فیلترشکن
          description: |
              Please specify the client version, mandatory for connection troubleshooting.<br>
              نسخه فیلترشکنی که استفاده می‌کنید را مشخص کنید، برای عیب‌یابی مشکلات اتصال الزامی است.
      validations:
          required: false